version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-vite-node-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - MONGO_URI=mongodb://mongodb:27017/vite-node-mongo
    depends_on:
      - mongodb
    command: pnpm dev

volumes:
  mongodb_data:
